---
title: "cpt2_16s"
output: html_document
date: "2023-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(BiocManager)
#BiocManager::install(c("ggside"))
library(tidyverse)

library(ape)
library(DESeq2)
library(lme4)
library(miLineage)
library(phangorn)
library(phyloseq)
library(vegan)
library(VennDiagram)
library(ggpubr)
library(MicrobiotaProcess)
library(gghalves)
library(ggh4x)
library(ggalluvial)
library(corrr)
library(ggthemes)
library(ggtree)
library(ggtreeExtra)
library(ggstar)
library(randomForest)
library(ggside)

select <- dplyr::select

```




```{r import}
metadata <- read_csv("metadata.csv")%>%
  column_to_rownames("sample_id")%>%
  mutate(sample_id = paste0("M",mouse,"_d",day,"_",genotype,"_",diet))%>%
  select(sample_id, everything())%>%
  mutate(mouse = as.factor(mouse))%>%
  mutate(day.factor = as.factor(day))
  


sd <- sample_data(metadata)
sample_names(sd) <- rownames(metadata)  
  

ps_rename <- setNames(metadata$sample_id, rownames(metadata))



ps <- import_mothur(
    mothur_shared_file = "stability.final.opti_mcc.shared",
    mothur_constaxonomy_file = "stability.final.opti_mcc.0.03.cons.taxonomy"
    )

tax_table <- read_tsv("stability.final.opti_mcc.0.03.cons.taxonomy")%>%
  separate(Taxonomy, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species", "Strain"), sep=";")%>%
  select(-c(Species, Strain))



mothur_ps <- ps%>%
  merge_phyloseq(sd)

sample_names(mothur_ps) <- sample_data(mothur_ps)$sample_id

sample_names(mothur_ps)
sample_sums(mothur_ps)
```

```{r mpse}

mpse = as.mpse(mothur_ps)%>%
  mutate(diet = fct_recode(diet,
                             "Low Fat" = "LF",
                             "High Fat" = "HF"))%>%
  mutate(diet = fct_relevel(diet, "Low Fat", "High Fat"))%>%
  
  mutate(genotype = fct_relevel(genotype, "WT", "KO"))%>%
  mp_rrarefy(raresize = 44546, trimOTU = TRUE, trimSample = TRUE)%>%
  mp_cal_rarecurve()%>%
  mp_cal_alpha()%>%
  mp_cal_abundance(.abundance = RareAbundance)%>%
  mp_cal_abundance(
      .abundance=RareAbundance,
      .group=c(day.factor,genotype,diet)
    )%>%

  mp_decostand(.abundance = Abundance)%>%
  mp_cal_dist(.abundance = hellinger, distmethod="bray")%>%
  mp_cal_nmds(.abundance = hellinger, distmethod = "bray")


#distinct(mpse, diet)
```

```{r }
# mpse = as.mpse(mothur_ps)%>%
# 
#   mp_rrarefy()%>%
#   mp_cal_rarecurve()%>%
#   mp_cal_alpha()%>%
#   #mp_cal_abundance(.abundance = RareAbundance)%>%
#   mp_cal_abundance(
#       .abundance=RareAbundance,
#       #.group=c("mouse")
#     )%>%
#   mp_cal_abundance(
#     .abundance=RareAbundance,
#     .group = mouse
#   )%>%
#   mp_decostand(.abundance = Abundance)

# mpse2 = as.mpse(mothur_ps)%>%
# 
#   mp_rrarefy()%>%
#   mp_cal_rarecurve()%>%
#   mp_cal_alpha()%>%
#   #mp_cal_abundance(.abundance = RareAbundance)%>%
#   mp_cal_abundance(
#       .abundance=RareAbundance,
#       .group=c("mouse")
#     )%>%
#   mp_cal_abundance(
#     .abundance=RareAbundance,
#     .group = mouse
#   )



mp_plot_alpha(mpse2,
              .alpha = c(Shannon,Chao1),
              .group = c(day.factor),
              test = NULL,
              )

#mp_plot_rarecurve(mpse, .rare = RareAbundanceRarecurve, .alpha = Observe, .group = day, plot.group = TRUE)
```



```{r plot alpha, fig.height=8, fig.width =12}
mp_plot_alpha(mpse,
              .alpha = c(Shannon,Chao1),
              .group = c(day.factor, genotype, diet),
              #test = NULL,
              step_increase = 0.2
              )+
  scale_fill_manual(values=c("#4E79A7", "#59A14F", "#F28E2B"))+
  scale_color_manual(values=c("#4E79A7", "#59A14F", "#F28E2B"))
ggsave("alpha.png")
  #geom_signif(comparisons = list(c("0","1"), c("1","3"), c("0","3")),  test="wilcox.test", textsize = 2)
```
```{r plot dist, fig.height = 8, fig.width = 12}

mp_plot_abundance(mpse, 
                  .abundance =RareAbundnace,
                  .group = c(day.factor,diet,genotype),
                  taxa.class = Rank6,
                  topn = 15,
                  plot.group = TRUE,
                  relative = TRUE
                  )
ggsave("top15genera.png")




mp_plot_abundance(mpse, 
                  .abundance =RareAbundnace,
                  .group = c(genotype,diet,day.factor),
                  taxa.class = Rank5,
                  topn = 15,
                  #plot.group = TRUE,
                  relative = TRUE
                  )

ggsave("top15micefamily.png")


```
```{r dist,  fig.height = 10, fig.width = 14}
mp_plot_dist(mpse, .distmethod = bray, .group = c(diet, day.factor, genotype))%>%
  set_scale_theme(
          x = scale_fill_manual(
                 values=c("#4E79A7", "#F28E2B"), 
                 guide = guide_legend(
                             keywidth = 1, 
                             keyheight = 0.5, 
                             title.theme = element_text(size=8),
                             label.theme = element_text(size=6)
                 )
              ), 
          aes_var = genotype # specific the name of variable 
       )



```


```{r lactococcus RC9}
lactococcus <- mothur_ps%>%
  subset_samples(day.factor == "0")%>%
  transform_sample_counts(function(counts) counts / sum(counts))%>%
  psmelt()%>%
  filter(OTU =="Otu00001")

ggplot(lactococcus, aes(x=mouse, y=Abundance, fill = genotype))+
  geom_col()
ggsave("lactococcus.png")





rikenella <- mothur_ps%>%
  subset_samples(day.factor == "0")%>%
  transform_sample_counts(function(counts) counts / sum(counts))%>%
  psmelt()%>%
  filter(OTU =="Otu00010")

ggplot(rikenella, aes(x=mouse, y=Abundance))+
  geom_col()
ggsave("rikenella.png")
```




```{r nmds}
mpse_ord_lf <- mpse%>%
  filter(diet == "Low Fat")%>%
  mp_cal_nmds(.abundance = hellinger, distmethod = "bray")

mpse_ord_hf <- mpse%>%
  filter(diet == "High Fat")%>%
  mp_cal_nmds(.abundance = hellinger, distmethod = "bray")


mp_plot_ord(mpse_ord_hf,
            .ord = nmds,
            .group = day.factor,
            .starshape  = genotype,
            )+
  scale_fill_manual(values=c("#4E79A7", "#59A14F", "#F28E2B"))
ggsave("nmds_HF.png")

mp_plot_ord(mpse_ord_lf,
            .ord = nmds,
            .group = day.factor,
            .starshape  = genotype,
            )+
  scale_fill_manual(values=c("#4E79A7", "#59A14F", "#F28E2B"))
ggsave("nmds_LF.png")




mpse_ord_hf_d1 <- mpse%>%
  filter(diet == "High Fat")%>%
  mp_cal_nmds(.abundance = hellinger, distmethod = "bray")%>%
  mp_envfit(.ord = NMDS, .env = day, action = "add")


mpse_ord_hf_d1%>%
  mp_mrpp(.abundance = hellinger, .group = c(day), action = "get")

mp_plot_ord(mpse_ord_hf_d1,
            .ord = nmds,
            .group = day.factor,
            .starshape  = genotype,
            show.envfit = TRUE,
            show.adonis = TRUE
            )+
  scale_fill_manual(values=c("#4E79A7", "#59A14F", "#F28E2B"))
```

```{r diff analysis}
mpse_diff_lf <- mpse_ord_lf%>%
  filter(day.factor == 3)%>%
  mp_cal_abundance(
    .abundance=RareAbundance,
    .group=genotype
  )%>%
  mp_diff_analysis(.abundance= RelRareAbundanceBySample,
                   .group = genotype,
                   first.test.alpha = 1,
                   second.test.alpha = 0.1)



mpse_diff_lf %>%
         mp_plot_diff_boxplot(
           .group = genotype,
           taxa.class = c(Rank6)
         ) %>%
         set_diff_boxplot_color(
           values = c("deepskyblue", "orange"),
           guide = guide_legend(title=NULL)
         )
ggsave("lf_boxplot.png")  


mpse_diff_hf <- mpse_ord_hf%>%
  filter(day.factor == 3)%>%
  mp_cal_abundance(
    .abundance=RareAbundance,
    .group=genotype
  )%>%
  mp_diff_analysis(.abundance= RelRareAbundanceBySample,
                   .group = genotype,
                   first.test.alpha = 1,
                   second.test.alpha = 0.1)


mpse_diff_hf %>%
         mp_plot_diff_boxplot(
           .group = genotype,
           taxa.class = c(Rank6)
         ) %>%
         set_diff_boxplot_color(
           values = c("deepskyblue", "orange"),
           guide = guide_legend(title=NULL)
         )
ggsave("hf_boxplot.png")

```

```{r }
mpse_diff_hf_day <- mpse_ord_hf%>%
  filter(day.factor != 1)%>%
  mutate(day.factor = fct_relevel(day.factor, "0","3"))%>%
  mutate(day.factor = fct_recode(day.factor, 
                                 "0" = "0",
                                 "3" = "3"))%>%
  mp_cal_abundance(
    .abundance=RareAbundance,
    .group=day.factor
  )%>%
  mp_diff_analysis(.abundance= RelRareAbundanceBySample,
                   .group = day.factor,
                   first.test.alpha = 0.05,
                   second.test.alpha = 0.01)


mpse_diff_hf_day %>%
         mp_plot_diff_boxplot(
           .group = day.factor,
           taxa.class = c(Rank6)
         ) %>%
         set_diff_boxplot_color(
           values = c("deepskyblue", "orange"),
           guide = guide_legend(title=NULL)
         )


mpse_diff_lf_day <- mpse_ord_lf%>%
  filter(day.factor != 1)%>%
  mp_cal_abundance(
    .abundance=RareAbundance,
    .group=day.factor
  )%>%
  mp_diff_analysis(.abundance= RelRareAbundanceBySample,
                   .group = day.factor,
                   first.test.alpha = 0.05,
                   second.test.alpha = 0.01)


mpse_diff_lf_day %>%
         mp_plot_diff_boxplot(
           .group = genotype,
           taxa.class = c(Rank6)
         ) %>%
         set_diff_boxplot_color(
           values = c("deepskyblue", "orange"),
           guide = guide_legend(title=NULL)
         )

```

